### ISSUE TITLE
Will not start with gdax

### ISSUE THREAD

**Issue by zachaller** [ctubio/Krypto-trading-bot#10]
When starting this gets thrown

````
14:31:43.247 coinbase FIX Initiator Start
14:31:43.260 coinbase FIX Logon Connected
14:31:43.363 main Unhandled exception! TypeError: Cannot read property 'mask' of undefined
    at Sender.frameAndSend (/home/zaller/Krypto-trading-bot/node_modules/gdax/node_modules/ws/lib/Sender.js:206:17)
    at /home/zaller/Krypto-trading-bot/node_modules/gdax/node_modules/ws/lib/Sender.js:126:12
    at /home/zaller/Krypto-trading-bot/node_modules/gdax/node_modules/ws/lib/PerMessageDeflate.js:313:5
    at afterWrite (_stream_writable.js:430:3)
    at onwrite (_stream_writable.js:421:7)
    at afterTransform (_stream_transform.js:102:3)
    at TransformState.afterTransform (_stream_transform.js:75:12)
    at Zlib.callback (zlib.js:471:7)
14:31:43.370 main All exiting event handlers have fired, exiting application.
14:31:43.370 main Exiting with code 0
````

**Comment by Camille92** [comment]
https://github.com/ctubio/Krypto-trading-bot/issues/3
