### ISSUE TITLE
Problem running on RaspberryPI 3

### ISSUE THREAD

**Issue by lejacobroy** [ctubio/Krypto-trading-bot#109]
Updated to the latest commit (the one I was running was 2 weeks ago, and had a memory leak), using 'npm run latest && make latest && make reinstall'
When I try to run ('node K') it it gives me this error : 
'Error: Error: /home/pi/Desktop/KEOS/app/server/lib/K.linux.57.node: wrong ELF class: ELFCLASS64
    at bindings (/home/pi/Desktop/KEOS/app/server/main.js:14:19)
    at Object.<anonymous> (/home/pi/Desktop/KEOS/app/server/main.js:16:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/Desktop/KEOS/K.js:2:1)
'
There seems to be a 64-32bits mismatch somewhere...

**Comment by ctubio** [comment]
feel free to donate a RaspberryPI 3 to implement support for RaspberryPI 3 :P 

sorry currently im not able to reproduce this; the app is now a mess of javascript and c++, im sure there are more than one mismatch somewhere...

**Comment by lejacobroy** [comment]
Thanks, i'll test with an older commit then!

**Comment by ctubio** [comment]
release 3 is free from c++ codes

**Comment by heduobacht** [comment]
I found a 64bit version of Debian for the Raspberry Pi 3 
https://github.com/bamarni/pi64
If you can live without a stable Wlan this image is good for testing.

I was trying to run the bot there but i stucked st this fault:
```
pi@raspberrypi:~/K$ nodejs K.js
K.linux.57
11:41:09.469 main Unhandled exception! Error: Error: /home/pi/K/app/server/lib/K.linux.57.node: cannot open shared object file: No such file or directory
    at bindings (/home/pi/K/app/server/main.js:16:19)
    at Object.<anonymous> (/home/pi/K/app/server/main.js:18:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/K/K.js:2:1)

```
Seems that Nodejs is not working correctly but could not figure out why.
There was a similar issue #174  where there was the wrong version of nodejs installed. Maybe there is a connection between these issues?

**Comment by ctubio** [comment]
seems like folder `/home/pi/K/app` doesn't exists; it is usualy created by `make install`, cna you maybe run `make install` manually and make sure `/home/pi/K/app` exists as well as `/home/pi/K/app/server/lib/K.linux.57.node` ?

**Comment by heduobacht** [comment]
I did myself many `make reinstall` and tried nearly everything what you mention on your Main description page.
Checked it right now.
Did a manual `make install` 

The Folder and the file are where they should be:
```
pi@raspberrypi:~/K/app/server/lib$ dir
K.linux.57.node    libmysqlclient.so.18      libpng16.so.16       libquickfix.so.16.0.1
libcrypto.so.1.1   libmysqlclient.so.18.0.0  libpng16.so.16.31.0  libssl.so.1.1
libK.so                 libpng16.a                       libquickfix.la       libstdc++.so.6
libmysqlclient.a   libpng16.la                      libquickfix.so       libstdc++.so.6.0.22
libmysqlclient.so  libpng16.so                   libquickfix.so.16

```
But still no success.
Even when I try `pi@raspberrypi:~/K$ sudo nodejs K.js` to avoid any read and write problems still the same error message.
