### ISSUE TITLE
Can't boot: Missing module:

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#11]
Ubuntu 16.04,

Logs:
```
module.js:472
    throw err;
    ^

Error: Cannot find module 'bson'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/K/node_modules/mongodb-core/index.js:1:74)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/K/node_modules/mongodb/index.js:2:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by Camille92** [comment]
Once bson is installed you also need require-optional to work properly :)
    throw err;
    ^

Error: Cannot find module 'require_optional'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/K/node_modules/mongodb-core/index.js:2:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/K/node_modules/mongodb/index.js:2:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

**Comment by ctubio** [comment]
rm -rf node_modules package-lock.json && git checkout . && npm install && cd node_modules/gdax && npm install ws@3.0.0 && cd../.. && npm restart

**Comment by ctubio** [comment]
sorry im not sure yet why mongodb misses bson after upgrade (maybe some shit at package-lock.json [but is an automatic generated file; or at least it is as of today]); so just fresh reinstall

**Comment by Camille92** [comment]
Yes I'm doing that! :)
