### ISSUE TITLE
GDAX exception

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#14]
Hi, just set up a new install this morning and I'm getting the following error after a few seconds of connecting to the GDAX exchange.

I have tried pulling v3.0 of the ws lib as I thought it may be the same as the closed issue, however this didn't resolve the error. 

10:33:15.546 coinbase FIX Initiator Start
10:33:16.862 coinbase FIX Logon Connected
10:33:16.872 main Event loop delay 800ms
10:33:16.872 stdev Unable to compute value
10:33:16.895 tbp recalculated 0.12240369842414277
10:33:31.358 main Unhandled exception! TypeError: Cannot read property 'sub' of undefined
    at Orderbook.prototype.match (/home/######/K/node_modules/gdax/lib/orderbook.js:142:28)
    at OrderbookSync.prototype.processMessage (/home/######/K/node_modules/gdax/lib/orderbook_sync.js:127:14)
    at OrderbookSync.prototype.onMessage (/home/######/K/node_modules/gdax/lib/orderbook_sync.js:51:12)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (/home/######/K/node_modules/gdax/node_modules/ws/lib/WebSocket.js:146:47)
    at Receiver.dataMessage (/home/######/K/node_modules/gdax/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/######/K/node_modules/gdax/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/######/K/node_modules/gdax/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/######/K/node_modules/gdax/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/######/K/node_modules/gdax/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)

**Comment by ctubio** [comment]
yep, since https://github.com/coinbase/gdax-node/commit/d85184e2c844fdbba5fc7a5182fce9294bd6197c
im about to fork and fix this other project too.. i hate broken dependencies

**Comment by CarlitoGrey** [comment]
Thanks for the quick fix, however it's now presenting a new exception:

14:01:56.346 main Unhandled exception! { AssertionError: '1a3f9955-40e1-4a8f-9b57-365aefa7dcc7' == '91fc5b81-1060-4d39-a2bb-3828ef5b3e46'
    at Orderbook.prototype.match (/home/#######/K2/node_modules/gdax/lib/orderbook.js:142:14)
    at OrderbookSync.prototype.processMessage (/home/#######/K2/node_modules/gdax/lib/orderbook_sync.js:127:14)
    at OrderbookSync.prototype.onMessage (/home/#######/K2/node_modules/gdax/lib/orderbook_sync.js:51:12)
    at emitOne (events.js:96:13)
    at WebSocket.emit (events.js:188:7)
    at Receiver._receiver.onmessage (/home/#######/K2/node_modules/ws/lib/WebSocket.js:146:47)
    at Receiver.dataMessage (/home/#######/K2/node_modules/ws/lib/Receiver.js:389:14)
    at Receiver.getData (/home/#######/K2/node_modules/ws/lib/Receiver.js:330:12)
    at Receiver.startLoop (/home/#######/K2/node_modules/ws/lib/Receiver.js:165:16)
    at Receiver.add (/home/#######/K2/node_modules/ws/lib/Receiver.js:139:10)
    at TLSSocket._ultron.on (/home/#######/K2/node_modules/ws/lib/WebSocket.js:142:22)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:547:20)
  name: 'AssertionError',
  actual: '1a3f9955-40e1-4a8f-9b57-365aefa7dcc7',
  expected: '91fc5b81-1060-4d39-a2bb-3828ef5b3e46',
  operator: '==',
  message: '\'1a3f9955-40e1-4a8f-9b57-365aefa7dcc7\' == \'91fc5b81-1060-4d39-a2bb-3828ef5b3e46\'',
  generatedMessage: true }

**Comment by ctubio** [comment]
let me run it for a while and see if i can reproduce it

**Comment by CarlitoGrey** [comment]
Ok so it runs without issue if I have no trades open when starting up if that helps...
