### ISSUE TITLE
Make Start Issue 

### ISSUE THREAD

**Issue by norahnerd** [ctubio/Krypto-trading-bot#145]
Hi, 

I'm attempting to run Krypto Trading Bot on Ubuntu 16.04 LTS.. I've followed all of the directions to the best of my ability (not very familiar with javascript) and when I run make start I keep getting error 127.. upon running node.js K.js, I get this output:

module.js:491
    throw err;
    ^

Error: Cannot find module './app/server/main.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/richard/K/K.js:2:1)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

It seems to me that I'm just missing something that I need to install, but I'm not sure what. Any help would be greatly appreciated

**Comment by ctubio** [comment]
`Error: Cannot find module './app/server/main.js'` means that the folder `app/` doesn't exists; it is supposed to be created by "make start" or "make install" or "make reinstall".

it must be some error while the application is installed, can you try to paste the installation log?
the execution log is useless cos just says that `app/` doesn't exists, but we need to know why by looking at the installation steps

**Comment by norahnerd** [comment]
running `make install` kept crashing my system... I deleted everything to do with K and then reinstalled, and its working now, thanks!
