### ISSUE TITLE
Bitfinex app crash if no market data

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#156]
```
12:05:43.431 main Unhandled exception! TypeError: Cannot read property 'size' of null
    at Object.getQuoteAtTopOfMarket (/home/dhc-user/K/app/server/quoting-styles/helpers.js:28:38)
    at AK47QuoteStyle.TopOfTheMarketQuoteStyle.GenerateQuote (/home/dhc-user/K/app/server/quoting-styles/top-join.js:9:38)
    at QuotingStyleRegistry.GenerateQuote (/home/dhc-user/K/app/server/quoting-styles/style-registry.js:17:87)
    at QuotingEngine.computeQuote (/home/dhc-user/K/app/server/quoting-engine.js:114:42)
    at QuotingEngine.recalcQuote (/home/dhc-user/K/app/server/quoting-engine.js:62:32)
```

**Comment by ctubio** [comment]
seems this was already fixed in latest commit (anyway will delete all current quoting-styles soOn)
