### ISSUE TITLE
Error libcurl.so.4: undefined symbol

### ISSUE THREAD

**Issue by Jorman** [ctubio/Krypto-trading-bot#158]
Hi, maybe I made some mistake, I'm out for vacancy and I tried to update to latest commit, so like always I do the make diff, but the bot won't restart, so I check up if all is ok and I think is but valgrind say some about libssh2

Here the log with the versions of program:
```
krypto@scw-c32fa0:~/K$ gcc --version
gcc (Ubuntu 7.2.0-1ubuntu1~16.04) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

krypto@scw-c32fa0:~/K$ g++ --version
g++ (Ubuntu 7.2.0-1ubuntu1~16.04) 7.2.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

krypto@scw-c32fa0:~/K$ node --version
v8.4.0
krypto@scw-c32fa0:~/K$ KCONFIG=gdax-btc-eur-3000 valgrind nodejs K.js
==13898== Memcheck, a memory error detector
==13898== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==13898== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==13898== Command: nodejs K.js
==13898==
==13898== Warning: set address range perms: large range [0x31ff4db03000, 0x31ff6db04000) (noaccess)
K.linux.57
/home/krypto/K/app/server/main.js:14
            throw new Error(e);
            ^

Error: Error: libssh2.so.1: cannot open shared object file: No such file or directory
    at bindings (/home/krypto/K/app/server/main.js:14:19)
    at Object.<anonymous> (/home/krypto/K/app/server/main.js:16:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/krypto/K/K.js:2:1)
==13898==
==13898== HEAP SUMMARY:
==13898==     in use at exit: 613,545 bytes in 1,906 blocks
==13898==   total heap usage: 350,907 allocs, 349,001 frees, 311,779,048 bytes allocated
==13898==
==13898== LEAK SUMMARY:
==13898==    definitely lost: 0 bytes in 0 blocks
==13898==    indirectly lost: 0 bytes in 0 blocks
==13898==      possibly lost: 1,720 bytes in 10 blocks
==13898==    still reachable: 611,825 bytes in 1,896 blocks
==13898==                       of which reachable via heuristic:
==13898==                         newarray           : 6,288 bytes in 6 blocks
==13898==         suppressed: 0 bytes in 0 blocks
==13898== Rerun with --leak-check=full to see details of leaked memory
==13898==
==13898== For counts of detected and suppressed errors, rerun with: -v
==13898== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
So I installed libssh2, then I recompiled all, but again don't start, here the valgrind
```
krypto@scw-c32fa0:~/K$ KCONFIG=gdax-btc-eur-3000 valgrind nodejs K.js
==21268== Memcheck, a memory error detector
==21268== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==21268== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==21268== Command: nodejs K.js
==21268==
==21268== Warning: set address range perms: large range [0xa9dd97a0000, 0xa9df97a1000) (noaccess)
K.linux.57
/home/krypto/K/app/server/main.js:14
            throw new Error(e);
            ^

Error: Error: /home/krypto/K/app/server/lib/libcurl.so.4: undefined symbol: libssh2_scp_recv2
    at bindings (/home/krypto/K/app/server/main.js:14:19)
    at Object.<anonymous> (/home/krypto/K/app/server/main.js:16:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/krypto/K/K.js:2:1)
==21268==
==21268== HEAP SUMMARY:
==21268==     in use at exit: 614,217 bytes in 1,908 blocks
==21268==   total heap usage: 351,104 allocs, 349,196 frees, 311,840,023 bytes allocated
==21268==
==21268== LEAK SUMMARY:
==21268==    definitely lost: 0 bytes in 0 blocks
==21268==    indirectly lost: 0 bytes in 0 blocks
==21268==      possibly lost: 1,720 bytes in 10 blocks
==21268==    still reachable: 612,497 bytes in 1,898 blocks
==21268==                       of which reachable via heuristic:
==21268==                         newarray           : 6,288 bytes in 6 blocks
==21268==         suppressed: 0 bytes in 0 blocks
==21268== Rerun with --leak-check=full to see details of leaked memory
==21268==
==21268== For counts of detected and suppressed errors, rerun with: -v
==21268== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
This time libcurl give error, but I check with ldd
```
krypto@scw-c32fa0:~/K$ ldd /home/krypto/K/app/server/lib/libcurl.so.4
        linux-vdso.so.1 =>  (0x00007ffebd577000)
        libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f775fdd1000)
        libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f775fbaf000)
        librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f775f993000)
        libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f775f76a000)
        libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f775f55c000)
        libssl.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 (0x00007f775f2f3000)
        libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007f775ee8f000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f775ec45000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f775e973000)
        libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f775e744000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f775e540000)
        liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f775e331000)
        libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f775e0e0000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f775dec6000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f775dca9000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f775d8df000)
        libunistring.so.0 => /usr/lib/x86_64-linux-gnu/libunistring.so.0 (0x00007f775d5c9000)
        libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f775d299000)
        libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f775d066000)
        libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f775ce30000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f775cbb0000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f775c8cf000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f775c6cb000)
        libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f775c4c0000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f775c2bc000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f775c0a1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7760277000)
        libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f775be86000)
        libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f775bc45000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f775b9e1000)
        libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f775b7ae000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f775b59b000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f775b387000)
        libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f775b17e000)
        libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f775aef4000)
        libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f775ac52000)
        libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f775aa1f000)
        libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f775a809000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f775a601000)
        libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f775a3d8000)
        libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f775a1c9000)
        libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f7759f7e000)
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f7759ca9000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f7759a71000)
```
Is strange because till some day ago all works
Any idea?

**Comment by ctubio** [comment]
can you please show the output of `ldd app/server/lib/K.linux.57.node`?
thanks¡'

**Comment by ctubio** [comment]
i just installed ina fresh ubuntu without issues, can you maybe try to `apt-get update && apt-get upgrade`?

**Comment by Jorman** [comment]
Seems all ok, system update. I'm on ubuntu 16.04
Here the log you ask
```
krypto@scw-c32fa0:~/K$ ldd app/server/lib/K.linux.57.node
        linux-vdso.so.1 =>  (0x00007fff4378f000)
        libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007ffb3add5000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ffb3abb8000)
        libssl.so.1.1 => /home/krypto/K/app/server/lib/libssl.so.1.1 (0x00007ffb3a94c000)
        libcrypto.so.1.1 => /home/krypto/K/app/server/lib/libcrypto.so.1.1 (0x00007ffb3a4b9000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ffb3a29f000)
        libpng16.so.16 => /home/krypto/K/app/server/lib/libpng16.so.16 (0x00007ffb3a06d000)
        libquickfix.so.16 => /home/krypto/K/app/server/lib/libquickfix.so.16 (0x00007ffb39d6c000)
        libcurl.so.4 => /home/krypto/K/app/server/lib/libcurl.so.4 (0x00007ffb39aec000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ffb397e3000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffb39419000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ffb3b4e4000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffb39215000)
        libmysqlclient.so.18 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 (0x00007ffb38cd2000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ffb3894a000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ffb38733000)
        libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007ffb3850d000)
        libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007ffb382eb000)
        librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007ffb380cf000)
        libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007ffb37ea6000)
        libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007ffb37c98000)
        libssl.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2 (0x00007ffb37a2f000)
        libcrypto.so.1.0.2 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007ffb375cb000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007ffb37381000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007ffb370af000)
        libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007ffb36e80000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007ffb36c7c000)
        liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007ffb36a6d000)
        libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007ffb3681c000)
        libunistring.so.0 => /usr/lib/x86_64-linux-gnu/libunistring.so.0 (0x00007ffb36506000)
        libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007ffb361d6000)
        libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007ffb35fa3000)
        libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007ffb35d6d000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007ffb35aed000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007ffb3580c000)
        libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007ffb35601000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007ffb353fd000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007ffb351e2000)
        libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007ffb34fc7000)
        libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007ffb34d86000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007ffb34b22000)
        libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007ffb348ef000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007ffb346dc000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007ffb344c8000)
        libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007ffb342bf000)
        libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007ffb34035000)
        libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007ffb33d93000)
        libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007ffb33b60000)
        libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007ffb3394a000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007ffb33742000)
        libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007ffb33519000)
        libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007ffb3330a000)
        libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007ffb330bf000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007ffb32e87000)
```
I don't know where is the problem

**Comment by ctubio** [comment]
can you see if the latest commit helps?

**Comment by Jorman** [comment]
Hi, I just tried to use the last commit, I removed all modules and reinstall all see the log:
```
krypto@scw-c32fa0:~/K$ rm -rf node_modules/
krypto@scw-c32fa0:~/K$ make reinstall
rm -rf app
git checkout .
git fetch
git merge FETCH_HEAD
Already up-to-date.
make[1]: Entering directory '/home/krypto/K'
make[2]: Entering directory '/home/krypto/K'
test -n "`command -v apt-get`" && sudo apt-get -y install g++ build-essential automake autoconf libtool libxml2 libxml2-dev zlib1g-dev libsqlite3-dev libcurl4-openssl-dev libssl-dev openssl stunnel python curl gzip imagemagick\
|| (test -n "`command -v yum`" && sudo yum -y install gcc-c++ automake autoconf libtool libxml2 libxml2-devel zlib-devel sqlite-devel libcurl-devel openssl openssl-devel zlib-devel stunnel python curl gzip imagemagick) \
|| (test -n "`command -v brew`" && (xcode-select --install || :) && (brew install automake autoconf libxml2 sqlite openssl zlib libuv stunnel python curl gzip imagemagick || brew upgrade || :))
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'stunnel4' instead of 'stunnel'
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
build-essential is already the newest version (12.1ubuntu2).
g++ is already the newest version (4:5.3.1-1ubuntu1).
gzip is already the newest version (1.6-4ubuntu1).
libsqlite3-dev is already the newest version (3.11.0-1ubuntu1).
libtool is already the newest version (2.4.6-0.1).
python is already the newest version (2.7.11-1).
stunnel4 is already the newest version (3:5.30-1).
curl is already the newest version (7.47.0-1ubuntu2.2).
imagemagick is already the newest version (8:6.8.9.9-7ubuntu5.9).
libcurl4-openssl-dev is already the newest version (7.47.0-1ubuntu2.2).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).
libxml2 is already the newest version (2.9.3+dfsg1-1ubuntu0.2).
libxml2-dev is already the newest version (2.9.3+dfsg1-1ubuntu0.2).
openssl is already the newest version (1.0.2g-1ubuntu4.8).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
sudo mkdir -p /data/db/
sudo chown `id -u` /data/db
make dist
make[3]: Entering directory '/home/krypto/K'
mkdir -p build app/server/lib
make json
make[4]: Entering directory '/home/krypto/K'
test -f build/json-v2.1.1/json.h || (mkdir -p build/json-v2.1.1 && curl -L https://github.com/nlohmann/json/releases/download/v2.1.1/json.hpp -o build/json-v2.1.1/json.h)
make[4]: Leaving directory '/home/krypto/K'
make png16
make[4]: Entering directory '/home/krypto/K'
test -d build/libpng-1.6.31 || (curl -L https://github.com/glennrp/libpng/archive/v1.6.31.tar.gz | tar xz -C build && cd build/libpng-1.6.31 && ./autogen.sh && ./configure --prefix=/home/krypto/K/build/libpng-1.6.31 && make && sudo make install)
cp build/libpng-1.6.31/lib/libpng16* app/server/lib
make[4]: Leaving directory '/home/krypto/K'
make uws
make[4]: Entering directory '/home/krypto/K'
test -d build/uWebSockets-0.14.3 || curl -L https://github.com/uNetworking/uWebSockets/archive/v0.14.3.tar.gz | tar xz -C build
make[4]: Leaving directory '/home/krypto/K'
for K in dist/lib/*; do chmod +x $K && cp $K app/server/lib; done
sudo cp dist/lib/libnghttp2.so.14 dist/lib/libidn2.so.0 dist/lib/libpsl.so.5 dist/lib/libssl.so.1.0.2 dist/lib/libcrypto.so.1.0.2 dist/lib/ dist/lib/libstdc++.so.6.0.22 dist/lib/libmysqlclient.* /usr/lib/x86_64-linux-gnu/ || :
cp: omitting directory 'dist/lib/'
make[3]: Leaving directory '/home/krypto/K'
make gdax -s
make[3]: Entering directory '/home/krypto/K'
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "Coinbase, Inc.", CN = *.gdax.com
verify return:1
DONE
make[3]: Leaving directory '/home/krypto/K'
make[3]: Entering directory '/home/krypto/K'
make[3]: Leaving directory '/home/krypto/K'
make[2]: Leaving directory '/home/krypto/K'
added 508 packages in 72.709s
make[2]: Entering directory '/home/krypto/K'
Building server files..
./node_modules/.bin/tsc --alwaysStrict -t ES6 -m commonjs --outDir app src/server/*.ts src/server/*/*.ts src/share/*.ts
DONE
Building client dynamic files..
./node_modules/.bin/tsc --alwaysStrict --experimentalDecorators -t ES6 -m commonjs --outDir app/pub/js src/client/*.ts src/share/*.ts
DONE
Building client static files..
cp -R src/pub/* app/pub/
DONE
Building client bundle file..
./node_modules/.bin/browserify -t [ babelify --presets [ babili es2016 ] ] app/pub/js/client/main.js app/pub/js/lib/*.js | ./node_modules/.bin/uglifyjs | gzip > app/pub/js/client/bundle.min.js
DONE
make[2]: Leaving directory '/home/krypto/K'
make[1]: Leaving directory '/home/krypto/K'

/home/krypto/K/node_modules/ts-node/src/index.ts:307
        throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
test/statistics_tests.ts (3,29): Cannot find module '../src/server/statistics'. (2307)
    at getOutput (/home/krypto/K/node_modules/ts-node/src/index.ts:307:15)
    at /home/krypto/K/node_modules/ts-node/src/index.ts:336:16
    at Object.compile (/home/krypto/K/node_modules/ts-node/src/index.ts:498:11)
    at Module.m._compile (/home/krypto/K/node_modules/ts-node/src/index.ts:392:43)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/krypto/K/node_modules/ts-node/src/index.ts:395:12)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /home/krypto/K/node_modules/mocha/lib/mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/krypto/K/node_modules/mocha/lib/mocha.js:227:14)
    at Mocha.run (/home/krypto/K/node_modules/mocha/lib/mocha.js:513:10)
    at Object.<anonymous> (/home/krypto/K/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
Makefile:218: recipe for target 'test' failed
make[1]: *** [test] Error 1
Makefile:140: recipe for target 'reinstall' failed
make: *** [reinstall] Error 2
```

**Comment by b-seite** [comment]
Hi,
i had the same problem this morning. 
This fixed it for me : b-seite@4c19af4761f5b772e68aa9b8033a977e65446e1a
seems to be an old and unused import from a .ts file that doesn't exist anymore

**Comment by ctubio** [comment]
yea that is only the test failing; `make start` should work but `make test` currently is broken

**Comment by Jorman** [comment]
Tnx I'll try
Remember also statistics_tests.ts  have statistics import
