### ISSUE TITLE
K.linux.57.node built vs. K.linux.51 required

### ISSUE THREAD

**Issue by jangrewe** [ctubio/Krypto-trading-bot#174]
When starting K.js, i get this error:

```
K.linux.51
/opt/tribeca/app/server/main.js:14
            throw new Error(e);
            ^

Error: Error: Cannot find module './lib/K.linux.51'
    at bindings (/opt/tribeca/app/server/main.js:14:19)
    at Object.<anonymous> (/opt/tribeca/app/server/main.js:16:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/tribeca/K.js:2:1)
```
That seems to be only fair, as `K.linux.51` really doesn't exist.
Unfortunately, `make install` only builds `K.linux.57`, and that doesn't seem to be usable when copied to the required filename (which was kinda expected to not work):

```
K.linux.51
/opt/tribeca/app/server/main.js:14
            throw new Error(e);
            ^

Error: Error: The module '/opt/tribeca/app/server/lib/K.linux.51.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 51. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at bindings (/opt/tribeca/app/server/main.js:14:19)
    at Object.<anonymous> (/opt/tribeca/app/server/main.js:16:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/tribeca/K.js:2:1)
```
I deleted both files, wiped `node_modules`, reinstalled, but it still only compiles `K.linux.57`.

**Comment by ctubio** [comment]
get node v8 at https://nodejs.org/en/download/package-manager/
dropped support for v7 long time ago

**Comment by jangrewe** [comment]
Oh, i thought V8 referred to the actual NodeJS engine, not the version v8 ... my bad.

**Comment by ctubio** [comment]
err.. i think https://github.com/ctubio/Krypto-trading-bot/blob/master/src/server/main.ts#L9 is not working, will fix soon, thanks'¡
