### ISSUE TITLE
Application Fail To Start

### ISSUE THREAD

**Issue by Pfahlf** [ctubio/Krypto-trading-bot#175]
Following the manual instruction I wasn't able to connect to the website. In fact, instead of starting the app with `forever` but with `node K.js ` gives the following error output:
```javascript 
jfks-mbp:Krypto-trading-bot jfk$ node K.js 
K.darwin.57
/Users/jfk/Krypto-trading-bot/app/server/main.js:14
            throw new Error(e);
            ^

Error: Error: Cannot find module './lib/K.darwin.57'
    at bindings (/Users/jfk/Krypto-trading-bot/app/server/main.js:14:19)
    at Object.<anonymous> (/Users/jfk/Krypto-trading-bot/app/server/main.js:16:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/jfk/Krypto-trading-bot/K.js:2:1)
```

node version v8.4.0 
OS: OSX Sierra

**Comment by ctubio** [comment]
https://github.com/ctubio/Krypto-trading-bot/issues/136
