### ISSUE TITLE
Server stable for about 5 seconds then exits, log inside

### ISSUE THREAD

**Issue by Sakatard** [ctubio/Krypto-trading-bot#176]
error: Script restart attempt #11
K.linux.57
07:32:57.481869 CF settings loaded from JSON file K OK.
07:32:57.482322 UI ready over HTTPS on external port 3000.
07:32:59.226795 GW bitfinex allows client IP.
07:32:59.226846 GW bitfinex:
- autoBot: yes
- pair: btcusd
- minTick: 0.10000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
07:32:59.227079 DB /data/db/K.4.0.82.db loaded OK.
07:32:59.228444 TBP = 0.00000000 BTC loaded from DB.
07:32:59.359201 Unable to calculate stats, missing fair value.
07:33:02.546 main Event loop delay 2600ms
07:33:02.547889 Unable to calculate stats, missing fair value.
07:33:02.548060 GW bitfinex WS Error, reconnecting..
07:33:03.547691 Unable to calculate stats, missing fair value.
07:33:04.548069 Unable to calculate stats, missing fair value.
07:33:05.548471 Unable to calculate stats, missing fair value.
07:33:06.548859 Unable to calculate stats, missing fair value.
07:33:07.755354 Unable to calculate stats, missing fair value.
07:33:08.755633 Unable to calculate stats, missing fair value.
07:33:09.366507 GW bitfinex WS Info {"event":"info","version":2}
07:33:09.756125 Unable to calculate stats, missing fair value.
07:33:09.765794 GW bitfinex WS Streaming channel 58:"trades"
07:33:09.775142 GW bitfinex Changed quoting state to Enabled.
07:33:09.775340 GW bitfinex WS Streaming orders "OK" 0:"auth"
07:33:10.041819 GW bitfinex WS Streaming channel 63077:"book"
07:33:10.044 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.047 main Attempting to cancel all open orders, please wait..
07:33:10.388 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.388 main Attempting to cancel all open orders, please wait..
07:33:10.388 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.388 main Attempting to cancel all open orders, please wait..
07:33:10.389 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.389 main Attempting to cancel all open orders, please wait..
07:33:10.389 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.389 main Attempting to cancel all open orders, please wait..
07:33:10.389 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.390 main Attempting to cancel all open orders, please wait..
07:33:10.755 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.755 main Attempting to cancel all open orders, please wait..
07:33:10.756 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:10.756 main Attempting to cancel all open orders, please wait..
07:33:10.756 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at Timeout.QuotingEngine.recalcQuote [as _onTimeout] (/root/K/app/server/quoting-engine.js:63:32)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
07:33:10.757 main Attempting to cancel all open orders, please wait..
07:33:11.160 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.160 main Attempting to cancel all open orders, please wait..
07:33:11.160 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.160 main Attempting to cancel all open orders, please wait..
07:33:11.161 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.161 main Attempting to cancel all open orders, please wait..
07:33:11.161 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.161 main Attempting to cancel all open orders, please wait..
07:33:11.533 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.533 main Attempting to cancel all open orders, please wait..
07:33:11.533 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.533 main Attempting to cancel all open orders, please wait..
07:33:11.534 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.534 main Attempting to cancel all open orders, please wait..
07:33:11.534 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.534 main Attempting to cancel all open orders, please wait..
07:33:11.534 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.534 main Attempting to cancel all open orders, please wait..
07:33:11.906 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.906 main Attempting to cancel all open orders, please wait..
07:33:11.907 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.907 main Attempting to cancel all open orders, please wait..
07:33:11.908 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.908 main Attempting to cancel all open orders, please wait..
07:33:11.909 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.909 main Attempting to cancel all open orders, please wait..
07:33:11.909 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.909 main Attempting to cancel all open orders, please wait..
07:33:11.910 main Unhandled exception! TypeError: Cannot read property 'baseAmount' of null
    at QuotingEngine.computeQuote (/root/K/app/server/quoting-engine.js:96:49)
    at QuotingEngine.recalcQuote (/root/K/app/server/quoting-engine.js:63:32)
07:33:11.910 main Attempting to cancel all open orders, please wait..
07:33:12.048 main Exit code 0
error: Forever detected script exited with code: 0

**Comment by Sakatard** [comment]
Tried another exchange and received this error

08:00:59.411347 CF settings loaded from JSON file K OK.
08:00:59.411702 UI ready over HTTPS on external port 3000.
08:00:59.411780 GW okcoin allows client IP.
08:00:59.411789 GW okcoin:
- autoBot: no
- pair: btc_usd
- minTick: 0.01000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
08:00:59.411903 DB /data/db/K.2.0.82.db loaded OK.
08:00:59.412449 TBP = 0.00000000 BTC loaded from DB.
08:00:59.547628 Unable to calculate stats, missing fair value.
08:01:00.548064 Unable to calculate stats, missing fair value.
08:01:00.739911 1 UI currently connected, last connection was from ::ffff:192.168.0.220
08:01:01.317977 GW okcoin WS Streaming channel ok_sub_spotusd_btc_depth_20 true
08:01:01.323115 GW okcoin WS Streaming channel ok_sub_spotusd_btc_trades true
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be number, but is null
error: Forever detected script was killed by signal: SIGABRT
error: Script restart attempt #4
K.linux.57

**Comment by ctubio** [comment]
watch for next commits, quoting-engine will be migrated soOn.

**Comment by ctubio** [comment]
just started rewriting the quoting engine, lets see how long it takes :dancer:

**Comment by Sakatard** [comment]
Thanks but still getting an error.

error: Script restart attempt #1
K.linux.57
08:51:33.166485 CF settings loaded from JSON file K OK.
08:51:33.166830 UI ready over HTTPS on external port 3000.
08:51:36.915313 GW bitfinex allows client IP.
08:51:36.915363 GW bitfinex:
- autoBot: no
- pair: btcusd
- minTick: 0.10000000
- minSize: 0.01000000
- makeFee: 0.00000000
- takeFee: 0.00000000
08:51:36.915561 DB /data/db/K.4.0.82.db loaded OK.
08:51:36.916589 TBP = 0.00000000 BTC loaded from DB.
08:51:36.934596 Unable to calculate quote, missing fair value.
08:51:37.902581 GW bitfinex WS Error, reconnecting..
08:51:37.927402 1 UI currently connected, last connection was from ::ffff:192.168.0.220
08:51:37.934574 Unable to calculate quote, missing fair value.
08:51:38.934544 Unable to calculate quote, missing fair value.
08:51:39.934977 Unable to calculate quote, missing fair value.
08:51:40.936447 Unable to calculate quote, missing fair value.
08:51:41.937227 Unable to calculate quote, missing fair value.
08:51:43.108532 Unable to calculate quote, missing fair value.
08:51:44.109284 Unable to calculate quote, missing fair value.
08:51:44.623476 GW bitfinex WS Info {"event":"info","version":2}
08:51:45.010965 GW bitfinex WS Streaming channel 65:"trades"
08:51:45.013151 GW bitfinex WS Streaming wallet and orders "OK" 0:"auth"
terminate called after throwing an instance of 'std::domain_error'
  what():  type must be string, but is null
08:51:45.019518 Errrror signal 6 Aborted
/root/Krypto-trading-bot/app/server/lib/K.linux.57.node(_ZN1K2EV3wtfEi+0x26)[0x7f3b62212b06]
/lib/x86_64-linux-gnu/libc.so.6(+0x36cb0)[0x7f3b645cecb0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f3b645cec37]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f3b645d2028]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x15d)[0x7f3b6512c0ad]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f066)[0x7f3b6512a066]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f0b1)[0x7f3b6512a0b1]
/usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0x8f2c9)[0x7f3b6512a2c9]
/root/Krypto-trading-bot/app/server/lib/K.linux.57.node(_ZNK8nlohmann10basic_jsonISt3mapSt6vectorNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEblmdSaNS_14adl_serializerEE3getIS8_S8_Li0EEET0_v+0xc6)[0x7f3b62215586]
/root/Krypto-trading-bot/app/server/lib/K.linux.57.node(_ZZN1K10GwBitfinex4bookEvENKUlPN3uWS9WebSocketILb0EEEPcmNS1_6OpCodeEE2_clES4_S5_mS6_+0xa79)[0x7f3b62282f19]

Please, copy and paste this error into a github issue.
If you agree, go to https://github.com/ctubio/Krypto-trading-bot/issues/new
08:51:45.020031 GW bitfinex Attempting to cancel all open orders, please wait..
error: Forever detected script was killed by signal: SIGABRT

**Comment by ctubio** [comment]
i belive this was already fixed in latests commits
