### ISSUE TITLE
glibc: symbol not found

### ISSUE THREAD

**Issue by itpropro** [ctubio/Krypto-trading-bot#197]
Hello,
I get this error, when running with make start and getting the output with node K:
00:44:12.113 main Unhandled exception! Error: Error: /home/adm/Krypto-trading-bot/app/server/lib/libquickfix.so.16: symbol _ZTTNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference
    at bindings (/home/adm/Krypto-trading-bot/app/server/main.js:14:19)
    at Object.<anonymous> (/home/adm/Krypto-trading-bot/app/server/main.js:16:3)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/adm/Krypto-trading-bot/K.js:2:1)

Im running on Ubuntu 14.04 LTS

**Comment by ctubio** [comment]
try Ubuntu 16 or Debian Stretch

**Comment by ctubio** [comment]
all the linker relations will be rewrited soOn'' hope Ubuntu 14 wil be supported then
