### ISSUE TITLE
E11000 duplicate key error index: tribeca.mkt.$_id_

### ISSUE THREAD

**Issue by ctubio** [ctubio/Krypto-trading-bot#23]
```
persister { MongoError: E11000 duplicate key error index: tribeca.mkt.$_id_  dup                                                                key: { : ObjectId('5951167bc9df0331fa366c80') }
    at Function.MongoError.create (/home/admin/K/node_modules/mongodb-core/lib/e                                                               rror.js:31:11)
    at toError (/home/admin/K/node_modules/mongodb/lib/utils.js:139:22)
    at /home/admin/K/node_modules/mongodb/lib/collection.js:669:23
    at handleCallback (/home/admin/K/node_modules/mongodb/lib/utils.js:120:56)
    at resultHandler (/home/admin/K/node_modules/mongodb/lib/bulk/ordered.js:421                                                               :14)
    at getLastErrorCallback (/home/admin/K/node_modules/mongodb-core/lib/wirepro                                                               tocol/2_4_support.js:466:18)
    at /home/admin/K/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'E11000 duplicate key error index: tribeca.mkt.$_id_  dup key: { : Ob                                                               jectId(\'5951167bc9df0331fa366c80\') }',
  driver: true,
  code: 11000,
  index: 0,
  errmsg: 'E11000 duplicate key error index: tribeca.mkt.$_id_  dup key: { : Obj                                                               ectId(\'5951167bc9df0331fa366c80\') }',
  getOperation: [Function],
  toJSON: [Function],
  toString: [Function] } Unable to insert mkt [ MarketStats {
    fv: 2218.65,
    bid: 2218.06,
    ask: 2219.27,
    time: 2017-06-26T14:12:59.120Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c80 },
  MarketStats {
    fv: 2218.65,
    bid: 2218.06,
    ask: 2219.27,
    time: 2017-06-26T14:13:00.120Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c81 },
  MarketStats {
    fv: 2218.65,
    bid: 2218.06,
    ask: 2219.27,
    time: 2017-06-26T14:13:01.120Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c82 },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:02.258Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c83 },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:03.357Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c84 },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:05.538Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c85 },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:07.279Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c86 },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:08.989Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c87 },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:12.755Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 5951167bc9df0331fa366c88 },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:15.927Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 59511688c9df0331fa366c8a },
  MarketStats {
    fv: 2218.78,
    bid: 2218.06,
    ask: 2219.51,
    time: 2017-06-26T14:13:18.297Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 59511688c9df0331fa366c8b },
  MarketStats {
    fv: 2218.83,
    bid: 2218.06,
    ask: 2219.6,
    time: 2017-06-26T14:13:24.578Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 59511688c9df0331fa366c8c },
  MarketStats {
    fv: 2219.06,
    bid: 2218.06,
    ask: 2220.07,
    time: 2017-06-26T14:13:27.088Z,
    exchange: 3,
    pair: CurrencyPair { base: 0, quote: 2 },
    _id: 59511688c9df0331fa366c8d },
  MarketStats {
    fv: 2219.06,
    bid: 2218.06,
    ask: 2220.07,
    time: 2017-06-26T14:13:28.807Z } ]
14:13:30.614 main Event loop delay 1300ms
14:13:33.299 main Event loop delay 2200ms
14:13:38.369 main Event loop delay 4600ms
14:13:39.044 main Event loop delay 200ms
14:13:43.257 main Event loop delay 3700ms
14:13:49.484 main Unhandled promise rejection! { MongoError: Invalid Operation,                                                                No operations in bulk
    at Function.MongoError.create (/home/admin/K/node_modules/mongodb-core/lib/e                                                               rror.js:31:11)
    at toError (/home/admin/K/node_modules/mongodb/lib/utils.js:139:22)
    at OrderedBulkOperation.execute (/home/admin/K/node_modules/mongodb/lib/bulk                                                               /ordered.js:503:11)
    at bulkWrite (/home/admin/K/node_modules/mongodb/lib/collection.js:664:8)
    at Collection.insertMany (/home/admin/K/node_modules/mongodb/lib/collection.                                                               js:534:44)
    at collection.(anonymous function).then.coll (/home/admin/K/app/server/persi                                                               ster.js:113:34)
    at tryCatcher (/home/admin/K/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/admin/K/node_modules/bluebird/js                                                               /release/promise.js:512:31)
    at Promise._settlePromise (/home/admin/K/node_modules/bluebird/js/release/pr                                                               omise.js:569:18)
    at Promise._settlePromiseCtx (/home/admin/K/node_modules/bluebird/js/release                                                               /promise.js:606:10)
    at Async._drainQueue (/home/admin/K/node_modules/bluebird/js/release/async.j                                                               s:138:12)
    at Async._drainQueues (/home/admin/K/node_modules/bluebird/js/release/async.                                                               js:143:10)
    at Immediate.Async.drainQueues (/home/admin/K/node_modules/bluebird/js/relea                                                               se/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
  name: 'MongoError',
  message: 'Invalid Operation, No operations in bulk',
  driver: true } Promise {
  _bitField: 18087936,
  _fulfillmentHandler0:
   { MongoError: Invalid Operation, No operations in bulk
       at Function.MongoError.create (/home/admin/K/node_modules/mongodb-core/li                                                               b/error.js:31:11)
       at toError (/home/admin/K/node_modules/mongodb/lib/utils.js:139:22)
       at OrderedBulkOperation.execute (/home/admin/K/node_modules/mongodb/lib/b                                                               ulk/ordered.js:503:11)
       at bulkWrite (/home/admin/K/node_modules/mongodb/lib/collection.js:664:8)
       at Collection.insertMany (/home/admin/K/node_modules/mongodb/lib/collecti                                                               on.js:534:44)
       at collection.(anonymous function).then.coll (/home/admin/K/app/server/pe                                                               rsister.js:113:34)
       at tryCatcher (/home/admin/K/node_modules/bluebird/js/release/util.js:16:                                                               23)
       at Promise._settlePromiseFromHandler (/home/admin/K/node_modules/bluebird                                                               /js/release/promise.js:512:31)
       at Promise._settlePromise (/home/admin/K/node_modules/bluebird/js/release                                                               /promise.js:569:18)
       at Promise._settlePromiseCtx (/home/admin/K/node_modules/bluebird/js/rele                                                               ase/promise.js:606:10)
       at Async._drainQueue (/home/admin/K/node_modules/bluebird/js/release/asyn                                                               c.js:138:12)
       at Async._drainQueues (/home/admin/K/node_modules/bluebird/js/release/asy                                                               nc.js:143:10)
       at Immediate.Async.drainQueues (/home/admin/K/node_modules/bluebird/js/re                                                               lease/async.js:17:14)
       at runCallback (timers.js:672:20)
       at tryOnImmediate (timers.js:645:5)
       at processImmediate [as _immediateCallback] (timers.js:617:5)
     name: 'MongoError',
     message: 'Invalid Operation, No operations in bulk',
     driver: true },
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }

```

**Comment by ctubio** [comment]
if is not already fixed will be fixed by forever :D
