### ISSUE TITLE
Timeout Exception?

### ISSUE THREAD

**Issue by CarlitoGrey** [ctubio/Krypto-trading-bot#26]
14:44:47.831 main Unhandled exception! TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:81:11)
    at Object.urlParse [as parse] (url.js:75:5)
    at WebSocket.initAsClient (/home/######/K/node_modules/ws/lib/WebSocket.js:530:25)
    at new WebSocket (/home/######/K/node_modules/ws/lib/WebSocket.js:70:20)
    at Timeout.prototype.connect [as _onTimeout] (/home/######/K/node_modules/gdax/lib/clients/websocket.js:37:19)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)

**Comment by ctubio** [comment]
what gateway/currency pairs is this?

it looks like a websocket error, i mean, connectivity error; nothing that the app can solve, but cannot say wihout knowing the gateway/pairs.

last days gdax failed nonstop, if is gdax, is because gdax was down.

**Comment by CarlitoGrey** [comment]
Yep GDAX: BTC/EUR.
