### ISSUE TITLE
Installing error ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#28]
Hi Carles,

I bump into that issue when I run the install (with --unsafe-perm):

```
Error: Cannot find module 'lodash.isplainobject' (While processing preset: "/K/node_modules/babel-preset-babili/lib/index.js") while parsing file: /K/app/pub/js/client/main.js
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/K/node_modules/babel-preset-babili/lib/index.js:7:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
up to date in 20.446s

```

It seems that the bot works (order sent) but I can't access the web UI. :S

**Comment by Camille92** [comment]
Well after installing that and like 15 babel plugins manually I got it up and running.

Btw apparently babel moved to babel-cli maybe you want to check that out :)

**Comment by ctubio** [comment]
yea just update all from ES2015 to ES2016; not sure if was you solution, but a removing node_modules/ and npm install usualy does the fix

**Comment by ctubio** [comment]
i never used `--unsafe-perm`; is in Dockerfile only

**Comment by ctubio** [comment]
we dont need babel-cli because we use babel as a transform of browserify; we dont run directly babel

**Comment by Camille92** [comment]
Okay no probs, I run unsafe-perm because I'm root!
