### ISSUE TITLE
(BUG) GDAX FIX not working

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#3]
Hello Carles,

I ran an update this morning and could not boot the GDAX botss.

Here is the log I get:
```
07:19:50.843 coinbase FIX Initiator Start
07:19:50.858 coinbase FIX Logon Connected
07:19:50.905 active Changed quoting mode to true
07:19:50.911 main Unhandled exception! TypeError: Cannot read property 'mask' of undefined
    at Sender.frameAndSend (/home/ubuntu/K/node_modules/gdax/node_modules/ws/lib/Sender.js:206:17)
    at /home/ubuntu/K/node_modules/gdax/node_modules/ws/lib/Sender.js:126:12
    at /home/ubuntu/K/node_modules/gdax/node_modules/ws/lib/PerMessageDeflate.js:313:5
    at afterWrite (_stream_writable.js:383:3)
    at onwrite (_stream_writable.js:374:7)
    at afterTransform (_stream_transform.js:79:3)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:625:5)
07:19:50.913 main All exiting event handlers have fired, exiting application.
07:19:50.913 main Exiting with code 0

```

**Comment by ctubio** [comment]
i think gdax lib is using an old ws lib, see `npm ls ws`, will try to fix soOn

many thanks for the report'¡

**Comment by Camille92** [comment]
Thanks !

Did you manage to get Gdax working for you with that ?

**Comment by ctubio** [comment]
meanwhile `cd node_modules/gdax && npm install ws@3.0.0` fixes it
