### ISSUE TITLE
Commit "Updated tbp loaded on boot from database to resolve #27." breaks K

### ISSUE THREAD

**Issue by Camille92** [ctubio/Krypto-trading-bot#36]
Hi Carles,

I ran a few tests to this Updated tbp loaded on boot from database to resolve #27. breaks K and gives something like that on boot.
```
4:28:22.082 main Unhandled rejection! TypeError: Cannot read property 'value' of undefined
    at new FairValueEngine (/K/app/server/fair-value.js:22:67)
    at Object.<anonymous> (/K/app/server/main.js:204:22)
    at Generator.next (<anonymous>)
    at fulfilled (/K/app/server/main.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7) Promise {
  <rejected> TypeError: Cannot read property 'value' of undefined
    at new FairValueEngine (/K/app/server/fair-value.js:22:67)
    at Object.<anonymous> (/K/app/server/main.js:204:22)
    at Generator.next (<anonymous>)
    at fulfilled (/K/app/server/main.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7) }
```

**Comment by Camille92** [comment]
Well just using a clean install + a bit of trying fixes the problem

**Comment by ctubio** [comment]
fixed in latest commits
