### ISSUE TITLE
Poloniex: tbp / Unhandled rejection! { Error: socket hang up

### ISSUE THREAD

**Issue by bunde83** [ctubio/Krypto-trading-bot#62]
Having the issue below, this happens after about 5-10 minutes of running K.js

18:01:02.889 tbp Unable to compute tbp [ qp | pos ] = [ true | false ]
18:01:02.899 main Event loop delay 400ms
18:01:10.799 main Event loop delay 7400ms
18:01:23.322 main Event loop delay 12000ms
18:01:24.202 main Event loop delay 400ms
18:01:30.112 main Event loop delay 5400ms
18:01:45.015 main Event loop delay 14400ms
18:01:46.004 main Event loop delay 500ms
18:01:46.025 main Unhandled rejection! { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' } Promise {
  <rejected> { Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1130:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1047:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9) code: 'ECONNRESET' } }

**Comment by ctubio** [comment]
im not running Poloniex currently but someday sOOn will lOOk at it
