### ISSUE TITLE
bot is disconnected (hitbtc SyntaxError: Unexpected token u in JSON at position 0)

### ISSUE THREAD

**Issue by yepla** [ctubio/Krypto-trading-bot#75]
Hello,
I have try to install the bot and run it on hitbtc exchange but on the web ui i see bot is disconnected !
When i start nodejs K.js i have this error:
```
03:41:13.556 main Unhandled exception! SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at WebSocketClient.HitBtcMarketDataGateway.onMessage [as internalOnMessage] (/home/yepla/Krypto-trading-bot/app/server/gateways/hitbtc.js:105:28)
    at native.client.group.onMessage (/home/yepla/Krypto-trading-bot/node_modules/uws/uws.js:57:15)
03:41:13.559 main Attempting to cancel all open orders, please wait..
hitbtc SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at WebSocketClient.HitBtcMarketDataGateway.onMessage [as internalOnMessage] (/home/yepla/Krypto-trading-bot/app/server/gateways/hitbtc.js:105:28)
    at native.client.group.onMessage (/home/yepla/Krypto-trading-bot/node_modules/uws/uws.js:57:15) Error parsing msg {"MarketDataIncrementalRefresh":{"seqNo":3005289,"symbol":"FCNBTC","exchangeStatus":"working","ask":[{"price":"0.000033","size":263014},{"price":"0.000034","size":475717}],"bid":[{"price":"0.000030","size":8187},{"price":"0.000029","size":5271}],"trade":[],"timestamp":1500349273314}}
```
for each market.
Note that for gdax the web ui work good !
Thanks for your help.

**Comment by ctubio** [comment]
i believe nobody cares about hitbtc cos nobody made any donation in order to support the development of hitbtc

**Comment by CarlitoGrey** [comment]
Carles, my donation for hitbtc still stands.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ctubio** [comment]
i need to open an account in hitbtc, hope for it after the fix of the TBP missing on boot

**Comment by ctubio** [comment]
![jgxtn](https://user-images.githubusercontent.com/1634027/28328572-4a9b1c1c-6be7-11e7-8060-070e201a6071.gif)

**Comment by CarlitoGrey** [comment]
Hey Carles, many thanks for taking a look at this. Seems it's hit one last bug, I've raised a separate issue. I'm just leaving work will tip you tonight or tomorrow morning!
