### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined at new TargetBasePositionManager

### ISSUE THREAD

**Issue by yepla** [ctubio/Krypto-trading-bot#87]
Hello,
I try to use the last version of the bot on poloniex echange but i have error when i start nodejs K.js.

17:03:07.649 main Unhandled rejection! TypeError: Cannot read property 'length' of undefined
    at new TargetBasePositionManager (/home/yepla/Krypto-trading-bot/app/server/position-management.js:61:20)
    at Object.<anonymous> (/home/yepla/Krypto-trading-bot/app/server/main.js:94:347)
    at Generator.next (<anonymous>)
    at fulfilled (/home/yepla/Krypto-trading-bot/app/server/main.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) Promise {
  <rejected> TypeError: Cannot read property 'length' of undefined
    at new TargetBasePositionManager (/home/yepla/Krypto-trading-bot/app/server/position-management.js:61:20)
    at Object.<anonymous> (/home/yepla/Krypto-trading-bot/app/server/main.js:94:347)
    at Generator.next (<anonymous>)
    at fulfilled (/home/yepla/Krypto-trading-bot/app/server/main.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7) }

Thanks for your help.

**Comment by yepla** [comment]
With the last commit the bot is now connected but i see DisabledQuotes in the order book does it s normal ?

**Comment by yepla** [comment]
DisabledQuotes disapear when i start trading all seems ok
